/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/macaroni.gltf -o src/components/Macaroni.jsx -r public 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/psychedelic-macaroni-910a2f90df3f442b8b3fcc5a4b7ad254
Title: Psychedelic Macaroni
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Macaroni({ hovered, ...props }) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/macaroni/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions.Animation) {
      if (hovered) {
        actions.Animation.reset().fadeIn(0.5).play()
      } else {
        actions.Animation.fadeOut(0.5)
      }
    }
    
    return () => {
      if (actions.Animation) {
        actions.Animation.fadeOut(0.5)
      }
    }
  }, [hovered, actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Torus001_0' position={[0, 0, -5.6]}>
                <mesh name='Object_4' geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus003_1' position={[0, 0, -5.6]}>
                <mesh name='Object_6' geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus004_2' position={[0, 0, -5.6]}>
                <mesh name='Object_8' geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus005_3' position={[0, 0, -5.6]}>
                <mesh name='Object_10' geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus006_4' position={[0, 0, -5.6]}>
                <mesh name='Object_12' geometry={nodes.Object_12.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus007_5' position={[0, 0, -5.6]}>
                <mesh name='Object_14' geometry={nodes.Object_14.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus008_6' position={[0, 0, -5.6]}>
                <mesh name='Object_16' geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus009_7' position={[0, 0, -5.6]}>
                <mesh name='Object_18' geometry={nodes.Object_18.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus002_8' position={[0, 0, -4]}>
                <mesh name='Object_20' geometry={nodes.Object_20.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus010_9' position={[0, 0, -4]}>
                <mesh name='Object_22' geometry={nodes.Object_22.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus011_10' position={[0, 0, -4]}>
                <mesh name='Object_24' geometry={nodes.Object_24.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus012_11' position={[0, 0, -4]}>
                <mesh name='Object_26' geometry={nodes.Object_26.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus013_12' position={[0, 0, -4]}>
                <mesh name='Object_28' geometry={nodes.Object_28.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus014_13' position={[0, 0, -4]}>
                <mesh name='Object_30' geometry={nodes.Object_30.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus015_14' position={[0, 0, -4]}>
                <mesh name='Object_32' geometry={nodes.Object_32.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus016_15' position={[0, 0, -4]}>
                <mesh name='Object_34' geometry={nodes.Object_34.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus017_16' position={[0, 0, -2.4]}>
                <mesh name='Object_36' geometry={nodes.Object_36.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus018_17' position={[0, 0, -2.4]}>
                <mesh name='Object_38' geometry={nodes.Object_38.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus019_18' position={[0, 0, -2.4]}>
                <mesh name='Object_40' geometry={nodes.Object_40.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus020_19' position={[0, 0, -2.4]}>
                <mesh name='Object_42' geometry={nodes.Object_42.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus021_20' position={[0, 0, -2.4]}>
                <mesh name='Object_44' geometry={nodes.Object_44.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus022_21' position={[0, 0, -2.4]}>
                <mesh name='Object_46' geometry={nodes.Object_46.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus023_22' position={[0, 0, -2.4]}>
                <mesh name='Object_48' geometry={nodes.Object_48.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus024_23' position={[0, 0, -2.4]}>
                <mesh name='Object_50' geometry={nodes.Object_50.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus025_24' position={[0, 0, -0.8]}>
                <mesh name='Object_52' geometry={nodes.Object_52.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus026_25' position={[0, 0, -0.8]}>
                <mesh name='Object_54' geometry={nodes.Object_54.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus027_26' position={[0, 0, -0.8]}>
                <mesh name='Object_56' geometry={nodes.Object_56.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus028_27' position={[0, 0, -0.8]}>
                <mesh name='Object_58' geometry={nodes.Object_58.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus029_28' position={[0, 0, -0.8]}>
                <mesh name='Object_60' geometry={nodes.Object_60.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus030_29' position={[0, 0, -0.8]}>
                <mesh name='Object_62' geometry={nodes.Object_62.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus031_30' position={[0, 0, -0.8]}>
                <mesh name='Object_64' geometry={nodes.Object_64.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus032_31' position={[0, 0, -0.8]}>
                <mesh name='Object_66' geometry={nodes.Object_66.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus033_32' position={[0, 0, 0.8]}>
                <mesh name='Object_68' geometry={nodes.Object_68.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus034_33' position={[0, 0, 0.8]}>
                <mesh name='Object_70' geometry={nodes.Object_70.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus035_34' position={[0, 0, 0.8]}>
                <mesh name='Object_72' geometry={nodes.Object_72.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus036_35' position={[0, 0, 0.8]}>
                <mesh name='Object_74' geometry={nodes.Object_74.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus037_36' position={[0, 0, 0.8]}>
                <mesh name='Object_76' geometry={nodes.Object_76.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus038_37' position={[0, 0, 0.8]}>
                <mesh name='Object_78' geometry={nodes.Object_78.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus039_38' position={[0, 0, 0.8]}>
                <mesh name='Object_80' geometry={nodes.Object_80.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus040_39' position={[0, 0, 0.8]}>
                <mesh name='Object_82' geometry={nodes.Object_82.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus041_40' position={[0, 0, 2.4]}>
                <mesh name='Object_84' geometry={nodes.Object_84.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus042_41' position={[0, 0, 2.4]}>
                <mesh name='Object_86' geometry={nodes.Object_86.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus043_42' position={[0, 0, 2.4]}>
                <mesh name='Object_88' geometry={nodes.Object_88.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus044_43' position={[0, 0, 2.4]}>
                <mesh name='Object_90' geometry={nodes.Object_90.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus045_44' position={[0, 0, 2.4]}>
                <mesh name='Object_92' geometry={nodes.Object_92.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus046_45' position={[0, 0, 2.4]}>
                <mesh name='Object_94' geometry={nodes.Object_94.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus047_46' position={[0, 0, 2.4]}>
                <mesh name='Object_96' geometry={nodes.Object_96.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus048_47' position={[0, 0, 2.4]}>
                <mesh name='Object_98' geometry={nodes.Object_98.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus049_48' position={[0, 0, 4]}>
                <mesh name='Object_100' geometry={nodes.Object_100.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus050_49' position={[0, 0, 4]}>
                <mesh name='Object_102' geometry={nodes.Object_102.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus051_50' position={[0, 0, 4]}>
                <mesh name='Object_104' geometry={nodes.Object_104.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus052_51' position={[0, 0, 4]}>
                <mesh name='Object_106' geometry={nodes.Object_106.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus053_52' position={[0, 0, 4]}>
                <mesh name='Object_108' geometry={nodes.Object_108.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus054_53' position={[0, 0, 4]}>
                <mesh name='Object_110' geometry={nodes.Object_110.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus055_54' position={[0, 0, 4]}>
                <mesh name='Object_112' geometry={nodes.Object_112.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus056_55' position={[0, 0, 4]}>
                <mesh name='Object_114' geometry={nodes.Object_114.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus057_56' position={[0, 0, 5.6]}>
                <mesh name='Object_116' geometry={nodes.Object_116.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus058_57' position={[0, 0, 5.6]}>
                <mesh name='Object_118' geometry={nodes.Object_118.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus059_58' position={[0, 0, 5.6]}>
                <mesh name='Object_120' geometry={nodes.Object_120.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus060_59' position={[0, 0, 5.6]}>
                <mesh name='Object_122' geometry={nodes.Object_122.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus061_60' position={[0, 0, 5.6]}>
                <mesh name='Object_124' geometry={nodes.Object_124.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus062_61' position={[0, 0, 5.6]}>
                <mesh name='Object_126' geometry={nodes.Object_126.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus063_62' position={[0, 0, 5.6]}>
                <mesh name='Object_128' geometry={nodes.Object_128.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus064_63' position={[0, 0, 5.6]}>
                <mesh name='Object_130' geometry={nodes.Object_130.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus065_73' position={[0, 3.6, 5.6]}>
                <mesh name='Object_132' geometry={nodes.Object_132.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus066_74' position={[0, 3.6, 5.6]}>
                <mesh name='Object_134' geometry={nodes.Object_134.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus067_75' position={[0, 3.6, 5.6]}>
                <mesh name='Object_136' geometry={nodes.Object_136.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus068_76' position={[0, 3.6, 5.6]}>
                <mesh name='Object_138' geometry={nodes.Object_138.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus069_77' position={[0, 3.6, 5.6]}>
                <mesh name='Object_140' geometry={nodes.Object_140.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus070_78' position={[0, 3.6, 5.6]}>
                <mesh name='Object_142' geometry={nodes.Object_142.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus071_79' position={[0, 3.6, 5.6]}>
                <mesh name='Object_144' geometry={nodes.Object_144.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus072_80' position={[0, 3.6, 5.6]}>
                <mesh name='Object_146' geometry={nodes.Object_146.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus073_81' position={[0, 3.6, 4]}>
                <mesh name='Object_148' geometry={nodes.Object_148.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus074_82' position={[0, 3.6, 4]}>
                <mesh name='Object_150' geometry={nodes.Object_150.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus075_83' position={[0, 3.6, 4]}>
                <mesh name='Object_152' geometry={nodes.Object_152.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus076_84' position={[0, 3.6, 4]}>
                <mesh name='Object_154' geometry={nodes.Object_154.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus077_85' position={[0, 3.6, 4]}>
                <mesh name='Object_156' geometry={nodes.Object_156.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus078_86' position={[0, 3.6, 4]}>
                <mesh name='Object_158' geometry={nodes.Object_158.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus079_87' position={[0, 3.6, 4]}>
                <mesh name='Object_160' geometry={nodes.Object_160.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus080_88' position={[0, 3.6, 4]}>
                <mesh name='Object_162' geometry={nodes.Object_162.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus081_89' position={[0, 3.6, 2.4]}>
                <mesh name='Object_164' geometry={nodes.Object_164.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus082_90' position={[0, 3.6, 2.4]}>
                <mesh name='Object_166' geometry={nodes.Object_166.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus083_91' position={[0, 3.6, 2.4]}>
                <mesh name='Object_168' geometry={nodes.Object_168.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus084_92' position={[0, 3.6, 2.4]}>
                <mesh name='Object_170' geometry={nodes.Object_170.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus085_93' position={[0, 3.6, 2.4]}>
                <mesh name='Object_172' geometry={nodes.Object_172.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus086_94' position={[0, 3.6, 2.4]}>
                <mesh name='Object_174' geometry={nodes.Object_174.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus087_95' position={[0, 3.6, 2.4]}>
                <mesh name='Object_176' geometry={nodes.Object_176.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus088_96' position={[0, 3.6, 2.4]}>
                <mesh name='Object_178' geometry={nodes.Object_178.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus089_97' position={[0, 3.6, 0.8]}>
                <mesh name='Object_180' geometry={nodes.Object_180.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus090_98' position={[0, 3.6, 0.8]}>
                <mesh name='Object_182' geometry={nodes.Object_182.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus091_99' position={[0, 3.6, 0.8]}>
                <mesh name='Object_184' geometry={nodes.Object_184.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus092_100' position={[0, 3.6, 0.8]}>
                <mesh name='Object_186' geometry={nodes.Object_186.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus093_101' position={[0, 3.6, 0.8]}>
                <mesh name='Object_188' geometry={nodes.Object_188.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus094_102' position={[0, 3.6, 0.8]}>
                <mesh name='Object_190' geometry={nodes.Object_190.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus095_103' position={[0, 3.6, 0.8]}>
                <mesh name='Object_192' geometry={nodes.Object_192.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus096_104' position={[0, 3.6, 0.8]}>
                <mesh name='Object_194' geometry={nodes.Object_194.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus097_105' position={[0, 3.6, -0.8]}>
                <mesh name='Object_196' geometry={nodes.Object_196.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus098_106' position={[0, 3.6, -0.8]}>
                <mesh name='Object_198' geometry={nodes.Object_198.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus099_107' position={[0, 3.6, -0.8]}>
                <mesh name='Object_200' geometry={nodes.Object_200.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus100_108' position={[0, 3.6, -0.8]}>
                <mesh name='Object_202' geometry={nodes.Object_202.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus101_109' position={[0, 3.6, -0.8]}>
                <mesh name='Object_204' geometry={nodes.Object_204.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus102_110' position={[0, 3.6, -0.8]}>
                <mesh name='Object_206' geometry={nodes.Object_206.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus103_111' position={[0, 3.6, -0.8]}>
                <mesh name='Object_208' geometry={nodes.Object_208.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus104_112' position={[0, 3.6, -0.8]}>
                <mesh name='Object_210' geometry={nodes.Object_210.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus105_113' position={[0, 3.6, -2.4]}>
                <mesh name='Object_212' geometry={nodes.Object_212.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus106_114' position={[0, 3.6, -2.4]}>
                <mesh name='Object_214' geometry={nodes.Object_214.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus107_115' position={[0, 3.6, -2.4]}>
                <mesh name='Object_216' geometry={nodes.Object_216.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus108_116' position={[0, 3.6, -2.4]}>
                <mesh name='Object_218' geometry={nodes.Object_218.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus109_117' position={[0, 3.6, -2.4]}>
                <mesh name='Object_220' geometry={nodes.Object_220.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus110_118' position={[0, 3.6, -2.4]}>
                <mesh name='Object_222' geometry={nodes.Object_222.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus111_119' position={[0, 3.6, -2.4]}>
                <mesh name='Object_224' geometry={nodes.Object_224.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus112_120' position={[0, 3.6, -2.4]}>
                <mesh name='Object_226' geometry={nodes.Object_226.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus113_121' position={[0, 3.6, -4]}>
                <mesh name='Object_228' geometry={nodes.Object_228.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus114_122' position={[0, 3.6, -4]}>
                <mesh name='Object_230' geometry={nodes.Object_230.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus115_123' position={[0, 3.6, -4]}>
                <mesh name='Object_232' geometry={nodes.Object_232.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus116_124' position={[0, 3.6, -4]}>
                <mesh name='Object_234' geometry={nodes.Object_234.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus117_125' position={[0, 3.6, -4]}>
                <mesh name='Object_236' geometry={nodes.Object_236.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus118_126' position={[0, 3.6, -4]}>
                <mesh name='Object_238' geometry={nodes.Object_238.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus119_127' position={[0, 3.6, -4]}>
                <mesh name='Object_240' geometry={nodes.Object_240.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus120_128' position={[0, 3.6, -4]}>
                <mesh name='Object_242' geometry={nodes.Object_242.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus121_129' position={[0, 3.6, -5.6]}>
                <mesh name='Object_244' geometry={nodes.Object_244.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus122_130' position={[0, 3.6, -5.6]}>
                <mesh name='Object_246' geometry={nodes.Object_246.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus123_131' position={[0, 3.6, -5.6]}>
                <mesh name='Object_248' geometry={nodes.Object_248.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus124_132' position={[0, 3.6, -5.6]}>
                <mesh name='Object_250' geometry={nodes.Object_250.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus125_133' position={[0, 3.6, -5.6]}>
                <mesh name='Object_252' geometry={nodes.Object_252.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus126_134' position={[0, 3.6, -5.6]}>
                <mesh name='Object_254' geometry={nodes.Object_254.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus127_135' position={[0, 3.6, -5.6]}>
                <mesh name='Object_256' geometry={nodes.Object_256.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name='Torus128_136' position={[0, 3.6, -5.6]}>
                <mesh name='Object_258' geometry={nodes.Object_258.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/macaroni/scene.gltf')
