/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/timetunnel/scene.gltf -o src/components/Timetunnel.jsx -r public 
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/timetunnel-very-fast-a93e93e3e41e49feac04747c6f540b05
Title: Timetunnel ( very fast )
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Timetunnel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/timetunnel/scene.gltf')
  const { actions } = useAnimations(animations, group)
  console.log('actions:  ', actions)

  useEffect(() => {
    actions['Take 001'].reset().fadeIn(0.5).play()
    return () => {
      actions['Take 001'].fadeOut(0.5)
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[Math.PI / 2, 0, 0]} scale={0.124}>
          <group name='49927d12aec14ae787d8f71bacec0cb6fbx' rotation={[-Math.PI, 0, 0]}>
            <group name='Object_2'>
              <group name='RootNode'>
                <group name='Box001' position={[0, 220, 40]}>
                  <group name='Group001' scale={[0.185, 3.577, 0.185]}>
                    <group name='Torus026' position={[-115.251, 0, 80.7]} rotation={[Math.PI, 0.96, -Math.PI]}>
                      <group name='Object_9' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus026_01_-_Default_0'
                          geometry={nodes['Torus026_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus027' position={[-107.779, 0, 90.438]} rotation={[Math.PI, 0.873, -Math.PI]}>
                      <group name='Object_12' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus027_01_-_Default_0'
                          geometry={nodes['Torus027_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus028' position={[-99.487, 0, 99.488]} rotation={[Math.PI, 0.785, -Math.PI]}>
                      <group name='Object_15' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus028_01_-_Default_0'
                          geometry={nodes['Torus028_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus010' position={[-99.487, 0, -99.487]} rotation={[0, Math.PI / 4, 0]}>
                      <group name='Object_18' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus010_01_-_Default_0'
                          geometry={nodes['Torus010_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus001' position={[0, 0, -140.696]}>
                      <group name='Object_21' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus001_01_-_Default_0'
                          geometry={nodes['Torus001_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus009' position={[-90.438, 0, -107.78]} rotation={[0, 0.698, 0]}>
                      <group name='Object_24' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus009_01_-_Default_0'
                          geometry={nodes['Torus009_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus011' position={[-107.78, 0, -90.438]} rotation={[0, 0.873, 0]}>
                      <group name='Object_27' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus011_01_-_Default_0'
                          geometry={nodes['Torus011_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus012' position={[-115.252, 0, -80.7]} rotation={[0, 0.96, 0]}>
                      <group name='Object_30' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus012_01_-_Default_0'
                          geometry={nodes['Torus012_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus013' position={[-121.846, 0, -70.348]} rotation={[0, Math.PI / 3, 0]}>
                      <group name='Object_33' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus013_01_-_Default_0'
                          geometry={nodes['Torus013_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus015' position={[-132.211, 0, -48.121]} rotation={[0, 1.222, 0]}>
                      <group name='Object_36' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus015_01_-_Default_0'
                          geometry={nodes['Torus015_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus014' position={[-127.514, 0, -59.461]} rotation={[0, 1.134, 0]}>
                      <group name='Object_39' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus014_01_-_Default_0'
                          geometry={nodes['Torus014_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus064' position={[99.485, 0, -99.489]} rotation={[0, -0.785, 0]}>
                      <group name='Object_42' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus064_01_-_Default_0'
                          geometry={nodes['Torus064_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus065' position={[90.436, 0, -107.781]} rotation={[0, -0.698, 0]}>
                      <group name='Object_45' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus065_01_-_Default_0'
                          geometry={nodes['Torus065_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus066' position={[80.698, 0, -115.253]} rotation={[0, -0.611, 0]}>
                      <group name='Object_48' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus066_01_-_Default_0'
                          geometry={nodes['Torus066_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus067' position={[70.346, 0, -121.848]} rotation={[0, -0.524, 0]}>
                      <group name='Object_51' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus067_01_-_Default_0'
                          geometry={nodes['Torus067_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus068' position={[59.458, 0, -127.515]} rotation={[0, -0.436, 0]}>
                      <group name='Object_54' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus068_01_-_Default_0'
                          geometry={nodes['Torus068_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus069' position={[48.118, 0, -132.212]} rotation={[0, -0.349, 0]}>
                      <group name='Object_57' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus069_01_-_Default_0'
                          geometry={nodes['Torus069_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus070' position={[36.412, 0, -135.903]} rotation={[0, -0.262, 0]}>
                      <group name='Object_60' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus070_01_-_Default_0'
                          geometry={nodes['Torus070_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus071' position={[24.428, 0, -138.559]} rotation={[0, -0.175, 0]}>
                      <group name='Object_63' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus071_01_-_Default_0'
                          geometry={nodes['Torus071_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus043' position={[70.349, 0, 121.846]} rotation={[Math.PI, -0.524, Math.PI]}>
                      <group name='Object_66' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus043_01_-_Default_0'
                          geometry={nodes['Torus043_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus044' position={[80.701, 0, 115.251]} rotation={[Math.PI, -0.611, Math.PI]}>
                      <group name='Object_69' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus044_01_-_Default_0'
                          geometry={nodes['Torus044_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus045' position={[90.439, 0, 107.779]} rotation={[Math.PI, -0.698, Math.PI]}>
                      <group name='Object_72' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus045_01_-_Default_0'
                          geometry={nodes['Torus045_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus072' position={[12.259, 0, -140.161]} rotation={[0, -0.087, 0]}>
                      <group name='Object_75' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus072_01_-_Default_0'
                          geometry={nodes['Torus072_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus041' position={[48.122, 0, 132.211]} rotation={[Math.PI, -0.349, Math.PI]}>
                      <group name='Object_78' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus041_01_-_Default_0'
                          geometry={nodes['Torus041_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus042' position={[59.462, 0, 127.514]} rotation={[Math.PI, -0.436, Math.PI]}>
                      <group name='Object_81' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus042_01_-_Default_0'
                          geometry={nodes['Torus042_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus036' position={[-12.261, 0, 140.161]} rotation={[Math.PI, 0.087, -Math.PI]}>
                      <group name='Object_84' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus036_01_-_Default_0'
                          geometry={nodes['Torus036_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus038' position={[12.264, 0, 140.161]} rotation={[Math.PI, -0.087, Math.PI]}>
                      <group name='Object_87' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus038_01_-_Default_0'
                          geometry={nodes['Torus038_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus037' position={[0.001, 0, 140.696]} rotation={[Math.PI, 0, Math.PI]}>
                      <group name='Object_90' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus037_01_-_Default_0'
                          geometry={nodes['Torus037_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus039' position={[24.433, 0, 138.559]} rotation={[Math.PI, -0.175, Math.PI]}>
                      <group name='Object_93' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus039_01_-_Default_0'
                          geometry={nodes['Torus039_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus040' position={[36.416, 0, 135.902]} rotation={[Math.PI, -0.262, Math.PI]}>
                      <group name='Object_96' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus040_01_-_Default_0'
                          geometry={nodes['Torus040_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus002' position={[-12.262, 0, -140.161]} rotation={[0, 0.087, 0]}>
                      <group name='Object_99' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus002_01_-_Default_0'
                          geometry={nodes['Torus002_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus006' position={[-59.461, 0, -127.514]} rotation={[0, 0.436, 0]}>
                      <group name='Object_102' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus006_01_-_Default_0'
                          geometry={nodes['Torus006_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus007' position={[-70.348, 0, -121.847]} rotation={[0, Math.PI / 6, 0]}>
                      <group name='Object_105' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus007_01_-_Default_0'
                          geometry={nodes['Torus007_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus005' position={[-48.121, 0, -132.211]} rotation={[0, Math.PI / 9, 0]}>
                      <group name='Object_108' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus005_01_-_Default_0'
                          geometry={nodes['Torus005_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus004' position={[-36.415, 0, -135.902]} rotation={[0, 0.262, 0]}>
                      <group name='Object_111' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus004_01_-_Default_0'
                          geometry={nodes['Torus004_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus008' position={[-80.7, 0, -115.252]} rotation={[0, 0.611, 0]}>
                      <group name='Object_114' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus008_01_-_Default_0'
                          geometry={nodes['Torus008_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus003' position={[-24.432, 0, -138.559]} rotation={[0, 0.175, 0]}>
                      <group name='Object_117' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus003_01_-_Default_0'
                          geometry={nodes['Torus003_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus029' position={[-90.437, 0, 107.78]} rotation={[Math.PI, 0.698, -Math.PI]}>
                      <group name='Object_120' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus029_01_-_Default_0'
                          geometry={nodes['Torus029_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus030' position={[-80.7, 0, 115.252]} rotation={[Math.PI, 0.611, -Math.PI]}>
                      <group name='Object_123' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus030_01_-_Default_0'
                          geometry={nodes['Torus030_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus031' position={[-70.348, 0, 121.847]} rotation={[Math.PI, 0.524, -Math.PI]}>
                      <group name='Object_126' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus031_01_-_Default_0'
                          geometry={nodes['Torus031_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus032' position={[-59.46, 0, 127.514]} rotation={[Math.PI, 0.436, -Math.PI]}>
                      <group name='Object_129' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus032_01_-_Default_0'
                          geometry={nodes['Torus032_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus034' position={[-36.414, 0, 135.902]} rotation={[Math.PI, 0.262, -Math.PI]}>
                      <group name='Object_132' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus034_01_-_Default_0'
                          geometry={nodes['Torus034_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus033' position={[-48.12, 0, 132.211]} rotation={[Math.PI, 0.349, -Math.PI]}>
                      <group name='Object_135' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus033_01_-_Default_0'
                          geometry={nodes['Torus033_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus035' position={[-24.431, 0, 138.559]} rotation={[Math.PI, 0.175, -Math.PI]}>
                      <group name='Object_138' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus035_01_-_Default_0'
                          geometry={nodes['Torus035_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus016' position={[-135.902, 0, -36.415]} rotation={[0, 1.309, 0]}>
                      <group name='Object_141' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus016_01_-_Default_0'
                          geometry={nodes['Torus016_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus017' position={[-138.559, 0, -24.432]} rotation={[0, 1.396, 0]}>
                      <group name='Object_144' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus017_01_-_Default_0'
                          geometry={nodes['Torus017_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus018' position={[-140.161, 0, -12.263]} rotation={[0, 1.484, 0]}>
                      <group name='Object_147' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus018_01_-_Default_0'
                          geometry={nodes['Torus018_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus019' position={[-140.696, 0, 0]} rotation={[0, 1.571, 0]}>
                      <group name='Object_150' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus019_01_-_Default_0'
                          geometry={nodes['Torus019_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus020' position={[-140.161, 0, 12.262]} rotation={[3.142, 1.484, -3.142]}>
                      <group name='Object_153' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus020_01_-_Default_0'
                          geometry={nodes['Torus020_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus021' position={[-138.559, 0, 24.432]} rotation={[3.142, 1.396, -3.142]}>
                      <group name='Object_156' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus021_01_-_Default_0'
                          geometry={nodes['Torus021_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus022' position={[-135.902, 0, 36.415]} rotation={[3.142, 1.309, -3.142]}>
                      <group name='Object_159' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus022_01_-_Default_0'
                          geometry={nodes['Torus022_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus023' position={[-132.211, 0, 48.121]} rotation={[3.142, 1.222, -3.142]}>
                      <group name='Object_162' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus023_01_-_Default_0'
                          geometry={nodes['Torus023_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus024' position={[-127.514, 0, 59.461]} rotation={[3.142, 1.134, -3.142]}>
                      <group name='Object_165' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus024_01_-_Default_0'
                          geometry={nodes['Torus024_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus025' position={[-121.846, 0, 70.348]} rotation={[Math.PI, Math.PI / 3, -Math.PI]}>
                      <group name='Object_168' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus025_01_-_Default_0'
                          geometry={nodes['Torus025_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus063' position={[107.778, 0, -90.44]} rotation={[0, -0.873, 0]}>
                      <group name='Object_171' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus063_01_-_Default_0'
                          geometry={nodes['Torus063_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus046' position={[99.488, 0, 99.486]} rotation={[Math.PI, -0.785, Math.PI]}>
                      <group name='Object_174' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus046_01_-_Default_0'
                          geometry={nodes['Torus046_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus047' position={[107.781, 0, 90.436]} rotation={[Math.PI, -0.873, Math.PI]}>
                      <group name='Object_177' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus047_01_-_Default_0'
                          geometry={nodes['Torus047_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus048' position={[115.253, 0, 80.699]} rotation={[Math.PI, -0.96, Math.PI]}>
                      <group name='Object_180' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus048_01_-_Default_0'
                          geometry={nodes['Torus048_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus049' position={[121.847, 0, 70.347]} rotation={[Math.PI, -1.047, Math.PI]}>
                      <group name='Object_183' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus049_01_-_Default_0'
                          geometry={nodes['Torus049_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus050' position={[127.515, 0, 59.459]} rotation={[3.142, -1.134, 3.142]}>
                      <group name='Object_186' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus050_01_-_Default_0'
                          geometry={nodes['Torus050_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus051' position={[132.212, 0, 48.119]} rotation={[3.142, -1.222, 3.142]}>
                      <group name='Object_189' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus051_01_-_Default_0'
                          geometry={nodes['Torus051_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus052' position={[135.903, 0, 36.413]} rotation={[3.142, -1.309, 3.142]}>
                      <group name='Object_192' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus052_01_-_Default_0'
                          geometry={nodes['Torus052_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus053' position={[138.559, 0, 24.43]} rotation={[3.142, -1.396, 3.142]}>
                      <group name='Object_195' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus053_01_-_Default_0'
                          geometry={nodes['Torus053_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus054' position={[140.161, 0, 12.26]} rotation={[3.142, -1.484, 3.142]}>
                      <group name='Object_198' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus054_01_-_Default_0'
                          geometry={nodes['Torus054_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus055' position={[140.696, 0, -0.002]} rotation={[0, -Math.PI / 2, 0]}>
                      <group name='Object_201' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus055_01_-_Default_0'
                          geometry={nodes['Torus055_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus056' position={[140.161, 0, -12.265]} rotation={[0, -1.484, 0]}>
                      <group name='Object_204' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus056_01_-_Default_0'
                          geometry={nodes['Torus056_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus057' position={[138.558, 0, -24.434]} rotation={[0, -1.396, 0]}>
                      <group name='Object_207' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus057_01_-_Default_0'
                          geometry={nodes['Torus057_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus058' position={[135.902, 0, -36.417]} rotation={[0, -1.309, 0]}>
                      <group name='Object_210' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus058_01_-_Default_0'
                          geometry={nodes['Torus058_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus059' position={[132.21, 0, -48.123]} rotation={[0, -1.222, 0]}>
                      <group name='Object_213' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus059_01_-_Default_0'
                          geometry={nodes['Torus059_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus060' position={[127.513, 0, -59.463]} rotation={[0, -1.134, 0]}>
                      <group name='Object_216' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus060_01_-_Default_0'
                          geometry={nodes['Torus060_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus061' position={[121.845, 0, -70.35]} rotation={[0, -1.047, 0]}>
                      <group name='Object_219' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus061_01_-_Default_0'
                          geometry={nodes['Torus061_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group name='Torus062' position={[115.25, 0, -80.702]} rotation={[0, -0.96, 0]}>
                      <group name='Object_222' rotation={[-1.745, Math.PI / 2, 0]}>
                        <mesh
                          name='Torus062_01_-_Default_0'
                          geometry={nodes['Torus062_01_-_Default_0'].geometry}
                          material={materials['01_-_Default']}
                        />
                      </group>
                    </group>
                    <group
                      name='Sphere001'
                      position={[0.055, 51.829, 0.003]}
                      rotation={[-Math.PI, -1.517, -Math.PI]}
                      scale={[4.363, 0.225, 4.363]}
                    >
                      <mesh
                        name='Sphere001_03_-_Default_0'
                        geometry={nodes['Sphere001_03_-_Default_0'].geometry}
                        material={materials['03_-_Default']}
                      />
                    </group>
                  </group>
                  <group name='Object_5' position={[0, 0, -1.969]}>
                    <mesh
                      name='Box001_02_-_Default_0'
                      geometry={nodes['Box001_02_-_Default_0'].geometry}
                      material={materials['02_-_Default']}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/timetunnel/scene.gltf')
